#!/bin/bash

python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python

python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python

python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python

python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python

python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python
python3 ./ppo_discrete.py
pkill Chrome
pkill python